#ifndef H_CFA_13
#define H_CFA_13

#include "cfa_base.hpp"

#include <vector>
#include <string>

#include "TChain.h"

class cfa_13: public cfa_base{
public:
  explicit cfa_13(const std::string &file);

  virtual void GetEntry(const long entry);

  virtual ~cfa_13();

  virtual Int_t const & EcalDeadCellTriggerPrimitivefilter_decision() const;
  virtual Int_t const & HBHENoisefilter_decision() const;
  virtual Int_t const & METFiltersfilter_decision() const;
  virtual UInt_t const & Njets_AK4() const;
  virtual UInt_t const & Nmc_final() const;
  virtual UInt_t const & Nmc_jets() const;
  virtual UInt_t const & Nmets() const;
  virtual std::vector<float>* const & els_full5x5_sigmaIetaIeta() const;
  virtual std::vector<bool>* const & els_isPF() const;
  virtual std::vector<int>* const & els_jet_ind() const;
  virtual std::vector<float>* const & els_pfIsolationR03_sumChargedHadronPt() const;
  virtual std::vector<float>* const & els_pfIsolationR03_sumNeutralHadronEt() const;
  virtual std::vector<float>* const & els_pfIsolationR03_sumPUPt() const;
  virtual std::vector<float>* const & els_pfIsolationR03_sumPhotonEt() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT10_energy() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT10_eta() const;
  virtual std::vector<std::vector<int> >* const & fastjets_AK4_R1p2_R0p5pT10_index() const;
  virtual std::vector<int>* const & fastjets_AK4_R1p2_R0p5pT10_nconstituents() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT10_phi() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT10_px() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT10_py() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT10_pz() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT15_energy() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT15_eta() const;
  virtual std::vector<std::vector<int> >* const & fastjets_AK4_R1p2_R0p5pT15_index() const;
  virtual std::vector<int>* const & fastjets_AK4_R1p2_R0p5pT15_nconstituents() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT15_phi() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT15_px() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT15_py() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT15_pz() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT20_energy() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT20_eta() const;
  virtual std::vector<std::vector<int> >* const & fastjets_AK4_R1p2_R0p5pT20_index() const;
  virtual std::vector<int>* const & fastjets_AK4_R1p2_R0p5pT20_nconstituents() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT20_phi() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT20_px() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT20_py() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT20_pz() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT25_energy() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT25_eta() const;
  virtual std::vector<std::vector<int> >* const & fastjets_AK4_R1p2_R0p5pT25_index() const;
  virtual std::vector<int>* const & fastjets_AK4_R1p2_R0p5pT25_nconstituents() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT25_phi() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT25_px() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT25_py() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT25_pz() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT30_energy() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT30_eta() const;
  virtual std::vector<std::vector<int> >* const & fastjets_AK4_R1p2_R0p5pT30_index() const;
  virtual std::vector<int>* const & fastjets_AK4_R1p2_R0p5pT30_nconstituents() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT30_phi() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT30_px() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT30_py() const;
  virtual std::vector<float>* const & fastjets_AK4_R1p2_R0p5pT30_pz() const;
  virtual Int_t const & goodVerticesfilter_decision() const;
  virtual std::vector<float>* const & jets_AK4_area() const;
  virtual std::vector<float>* const & jets_AK4_btag_TC_highEff() const;
  virtual std::vector<float>* const & jets_AK4_btag_TC_highPur() const;
  virtual std::vector<float>* const & jets_AK4_btag_jetBProb() const;
  virtual std::vector<float>* const & jets_AK4_btag_jetProb() const;
  virtual std::vector<float>* const & jets_AK4_btag_secVertexCombined() const;
  virtual std::vector<float>* const & jets_AK4_btag_secVertexHighEff() const;
  virtual std::vector<float>* const & jets_AK4_btag_secVertexHighPur() const;
  virtual std::vector<float>* const & jets_AK4_btag_softEle() const;
  virtual std::vector<float>* const & jets_AK4_btag_softMuon() const;
  virtual std::vector<float>* const & jets_AK4_chgEmE() const;
  virtual std::vector<float>* const & jets_AK4_chgHadE() const;
  virtual std::vector<float>* const & jets_AK4_chgMuE() const;
  virtual std::vector<float>* const & jets_AK4_chg_Mult() const;
  virtual std::vector<float>* const & jets_AK4_corrFactorRaw() const;
  virtual std::vector<float>* const & jets_AK4_ehf() const;
  virtual std::vector<int>* const & jets_AK4_el_ind() const;
  virtual std::vector<float>* const & jets_AK4_emf() const;
  virtual std::vector<float>* const & jets_AK4_energy() const;
  virtual std::vector<float>* const & jets_AK4_et() const;
  virtual std::vector<float>* const & jets_AK4_eta() const;
  virtual std::vector<float>* const & jets_AK4_etaetaMoment() const;
  virtual std::vector<float>* const & jets_AK4_etaphiMoment() const;
  virtual std::vector<float>* const & jets_AK4_fHPD() const;
  virtual std::vector<float>* const & jets_AK4_fRBX() const;
  virtual std::vector<float>* const & jets_AK4_fSubDetector1() const;
  virtual std::vector<float>* const & jets_AK4_fSubDetector2() const;
  virtual std::vector<float>* const & jets_AK4_fSubDetector3() const;
  virtual std::vector<float>* const & jets_AK4_fSubDetector4() const;
  virtual std::vector<float>* const & jets_AK4_gen_Energy() const;
  virtual std::vector<float>* const & jets_AK4_gen_Id() const;
  virtual std::vector<float>* const & jets_AK4_gen_et() const;
  virtual std::vector<float>* const & jets_AK4_gen_eta() const;
  virtual std::vector<float>* const & jets_AK4_gen_mass() const;
  virtual std::vector<float>* const & jets_AK4_gen_motherID() const;
  virtual std::vector<float>* const & jets_AK4_gen_phi() const;
  virtual std::vector<float>* const & jets_AK4_gen_pt() const;
  virtual std::vector<float>* const & jets_AK4_gen_threeCharge() const;
  virtual std::vector<float>* const & jets_AK4_hitsInN90() const;
  virtual std::vector<float>* const & jets_AK4_jetCharge() const;
  virtual std::vector<float>* const & jets_AK4_mass() const;
  virtual std::vector<int>* const & jets_AK4_maxpt_id() const;
  virtual std::vector<float>* const & jets_AK4_mu_Mult() const;
  virtual std::vector<int>* const & jets_AK4_mu_ind() const;
  virtual std::vector<float>* const & jets_AK4_n60() const;
  virtual std::vector<float>* const & jets_AK4_n90() const;
  virtual std::vector<float>* const & jets_AK4_n90Hits() const;
  virtual std::vector<float>* const & jets_AK4_nECALTowers() const;
  virtual std::vector<float>* const & jets_AK4_nHCALTowers() const;
  virtual std::vector<float>* const & jets_AK4_neutralEmE() const;
  virtual std::vector<float>* const & jets_AK4_neutralHadE() const;
  virtual std::vector<float>* const & jets_AK4_neutral_Mult() const;
  virtual std::vector<float>* const & jets_AK4_partonFlavour() const;
  virtual std::vector<float>* const & jets_AK4_parton_Energy() const;
  virtual std::vector<float>* const & jets_AK4_parton_Id() const;
  virtual std::vector<float>* const & jets_AK4_parton_eta() const;
  virtual std::vector<float>* const & jets_AK4_parton_mass() const;
  virtual std::vector<float>* const & jets_AK4_parton_motherId() const;
  virtual std::vector<float>* const & jets_AK4_parton_phi() const;
  virtual std::vector<float>* const & jets_AK4_parton_pt() const;
  virtual std::vector<float>* const & jets_AK4_phi() const;
  virtual std::vector<float>* const & jets_AK4_phiphiMoment() const;
  virtual std::vector<float>* const & jets_AK4_photonEnergy() const;
  virtual std::vector<float>* const & jets_AK4_pt() const;
  virtual std::vector<float>* const & jets_AK4_px() const;
  virtual std::vector<float>* const & jets_AK4_py() const;
  virtual std::vector<float>* const & jets_AK4_pz() const;
  virtual std::vector<float>* const & jets_AK4_rawPt() const;
  virtual std::vector<float>* const & jets_AK4_status() const;
  virtual std::vector<float>* const & jets_AK4_theta() const;
  virtual std::vector<float>* const & mc_final_charge() const;
  virtual std::vector<float>* const & mc_final_energy() const;
  virtual std::vector<float>* const & mc_final_eta() const;
  virtual std::vector<float>* const & mc_final_ggrandmother_id() const;
  virtual std::vector<float>* const & mc_final_grandmother_id() const;
  virtual std::vector<float>* const & mc_final_id() const;
  virtual std::vector<float>* const & mc_final_mass() const;
  virtual std::vector<float>* const & mc_final_mother_id() const;
  virtual std::vector<float>* const & mc_final_mother_pt() const;
  virtual std::vector<float>* const & mc_final_numOfDaughters() const;
  virtual std::vector<float>* const & mc_final_numOfMothers() const;
  virtual std::vector<float>* const & mc_final_phi() const;
  virtual std::vector<float>* const & mc_final_pt() const;
  virtual std::vector<float>* const & mc_final_px() const;
  virtual std::vector<float>* const & mc_final_py() const;
  virtual std::vector<float>* const & mc_final_pz() const;
  virtual std::vector<float>* const & mc_final_status() const;
  virtual std::vector<float>* const & mc_final_theta() const;
  virtual std::vector<float>* const & mc_final_vertex_x() const;
  virtual std::vector<float>* const & mc_final_vertex_y() const;
  virtual std::vector<float>* const & mc_final_vertex_z() const;
  virtual std::vector<float>* const & mc_jets_auxiliaryEnergy() const;
  virtual std::vector<float>* const & mc_jets_emEnergy() const;
  virtual std::vector<float>* const & mc_jets_energy() const;
  virtual std::vector<float>* const & mc_jets_et() const;
  virtual std::vector<float>* const & mc_jets_eta() const;
  virtual std::vector<float>* const & mc_jets_etaetaMoment() const;
  virtual std::vector<float>* const & mc_jets_etaphiMoment() const;
  virtual std::vector<float>* const & mc_jets_hadEnergy() const;
  virtual std::vector<float>* const & mc_jets_invisibleEnergy() const;
  virtual std::vector<float>* const & mc_jets_mass() const;
  virtual std::vector<float>* const & mc_jets_phi() const;
  virtual std::vector<float>* const & mc_jets_phiphiMoment() const;
  virtual std::vector<float>* const & mc_jets_pt() const;
  virtual std::vector<float>* const & mc_jets_px() const;
  virtual std::vector<float>* const & mc_jets_py() const;
  virtual std::vector<float>* const & mc_jets_pz() const;
  virtual std::vector<float>* const & mc_jets_theta() const;
  virtual std::vector<float>* const & mets_et() const;
  virtual std::vector<float>* const & mets_ex() const;
  virtual std::vector<float>* const & mets_ey() const;
  virtual std::vector<float>* const & mets_gen_et() const;
  virtual std::vector<float>* const & mets_gen_phi() const;
  virtual std::vector<float>* const & mets_phi() const;
  virtual std::vector<float>* const & mets_sign() const;
  virtual std::vector<float>* const & mets_sumEt() const;
  virtual std::vector<float>* const & mets_unCPhi() const;
  virtual std::vector<float>* const & mets_unCPt() const;
  virtual std::vector<bool>* const & mus_isPF() const;
  virtual std::vector<int>* const & mus_jet_ind() const;
  virtual std::vector<int>* const & taus_el_ind() const;
  virtual std::vector<int>* const & taus_mu_ind() const;
  virtual std::vector<bool>* const & trigger_decision() const;
  virtual Int_t const & trkPOG_logErrorTooManyClustersfilter_decision() const;
  virtual Int_t const & trkPOG_manystripclus53Xfilter_decision() const;
  virtual Int_t const & trkPOG_toomanystripclus53Xfilter_decision() const;
  virtual Int_t const & trkPOGfilter_decision() const;

private:
  virtual void InitializeA();
  virtual void InitializeB();

  mutable Int_t EcalDeadCellTriggerPrimitivefilter_decision_;
  mutable TBranch *b_EcalDeadCellTriggerPrimitivefilter_decision_;
  mutable bool c_EcalDeadCellTriggerPrimitivefilter_decision_;
  mutable Int_t HBHENoisefilter_decision_;
  mutable TBranch *b_HBHENoisefilter_decision_;
  mutable bool c_HBHENoisefilter_decision_;
  mutable Int_t METFiltersfilter_decision_;
  mutable TBranch *b_METFiltersfilter_decision_;
  mutable bool c_METFiltersfilter_decision_;
  mutable UInt_t Njets_AK4_;
  mutable TBranch *b_Njets_AK4_;
  mutable bool c_Njets_AK4_;
  mutable UInt_t Nmc_final_;
  mutable TBranch *b_Nmc_final_;
  mutable bool c_Nmc_final_;
  mutable UInt_t Nmc_jets_;
  mutable TBranch *b_Nmc_jets_;
  mutable bool c_Nmc_jets_;
  mutable UInt_t Nmets_;
  mutable TBranch *b_Nmets_;
  mutable bool c_Nmets_;
  mutable std::vector<float>* els_full5x5_sigmaIetaIeta_;
  mutable TBranch *b_els_full5x5_sigmaIetaIeta_;
  mutable bool c_els_full5x5_sigmaIetaIeta_;
  mutable std::vector<bool>* els_isPF_;
  mutable TBranch *b_els_isPF_;
  mutable bool c_els_isPF_;
  mutable std::vector<int>* els_jet_ind_;
  mutable TBranch *b_els_jet_ind_;
  mutable bool c_els_jet_ind_;
  mutable std::vector<float>* els_pfIsolationR03_sumChargedHadronPt_;
  mutable TBranch *b_els_pfIsolationR03_sumChargedHadronPt_;
  mutable bool c_els_pfIsolationR03_sumChargedHadronPt_;
  mutable std::vector<float>* els_pfIsolationR03_sumNeutralHadronEt_;
  mutable TBranch *b_els_pfIsolationR03_sumNeutralHadronEt_;
  mutable bool c_els_pfIsolationR03_sumNeutralHadronEt_;
  mutable std::vector<float>* els_pfIsolationR03_sumPUPt_;
  mutable TBranch *b_els_pfIsolationR03_sumPUPt_;
  mutable bool c_els_pfIsolationR03_sumPUPt_;
  mutable std::vector<float>* els_pfIsolationR03_sumPhotonEt_;
  mutable TBranch *b_els_pfIsolationR03_sumPhotonEt_;
  mutable bool c_els_pfIsolationR03_sumPhotonEt_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT10_energy_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_energy_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_energy_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT10_eta_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_eta_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_eta_;
  mutable std::vector<std::vector<int> >* fastjets_AK4_R1p2_R0p5pT10_index_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_index_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_index_;
  mutable std::vector<int>* fastjets_AK4_R1p2_R0p5pT10_nconstituents_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_nconstituents_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_nconstituents_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT10_phi_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_phi_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_phi_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT10_px_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_px_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_px_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT10_py_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_py_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_py_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT10_pz_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT10_pz_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT10_pz_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT15_energy_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_energy_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_energy_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT15_eta_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_eta_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_eta_;
  mutable std::vector<std::vector<int> >* fastjets_AK4_R1p2_R0p5pT15_index_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_index_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_index_;
  mutable std::vector<int>* fastjets_AK4_R1p2_R0p5pT15_nconstituents_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_nconstituents_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_nconstituents_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT15_phi_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_phi_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_phi_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT15_px_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_px_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_px_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT15_py_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_py_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_py_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT15_pz_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT15_pz_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT15_pz_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT20_energy_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_energy_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_energy_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT20_eta_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_eta_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_eta_;
  mutable std::vector<std::vector<int> >* fastjets_AK4_R1p2_R0p5pT20_index_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_index_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_index_;
  mutable std::vector<int>* fastjets_AK4_R1p2_R0p5pT20_nconstituents_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_nconstituents_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_nconstituents_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT20_phi_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_phi_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_phi_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT20_px_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_px_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_px_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT20_py_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_py_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_py_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT20_pz_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT20_pz_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT20_pz_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT25_energy_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_energy_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_energy_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT25_eta_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_eta_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_eta_;
  mutable std::vector<std::vector<int> >* fastjets_AK4_R1p2_R0p5pT25_index_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_index_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_index_;
  mutable std::vector<int>* fastjets_AK4_R1p2_R0p5pT25_nconstituents_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_nconstituents_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_nconstituents_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT25_phi_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_phi_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_phi_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT25_px_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_px_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_px_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT25_py_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_py_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_py_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT25_pz_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT25_pz_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT25_pz_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT30_energy_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_energy_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_energy_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT30_eta_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_eta_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_eta_;
  mutable std::vector<std::vector<int> >* fastjets_AK4_R1p2_R0p5pT30_index_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_index_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_index_;
  mutable std::vector<int>* fastjets_AK4_R1p2_R0p5pT30_nconstituents_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_nconstituents_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_nconstituents_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT30_phi_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_phi_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_phi_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT30_px_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_px_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_px_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT30_py_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_py_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_py_;
  mutable std::vector<float>* fastjets_AK4_R1p2_R0p5pT30_pz_;
  mutable TBranch *b_fastjets_AK4_R1p2_R0p5pT30_pz_;
  mutable bool c_fastjets_AK4_R1p2_R0p5pT30_pz_;
  mutable Int_t goodVerticesfilter_decision_;
  mutable TBranch *b_goodVerticesfilter_decision_;
  mutable bool c_goodVerticesfilter_decision_;
  mutable std::vector<float>* jets_AK4_area_;
  mutable TBranch *b_jets_AK4_area_;
  mutable bool c_jets_AK4_area_;
  mutable std::vector<float>* jets_AK4_btag_TC_highEff_;
  mutable TBranch *b_jets_AK4_btag_TC_highEff_;
  mutable bool c_jets_AK4_btag_TC_highEff_;
  mutable std::vector<float>* jets_AK4_btag_TC_highPur_;
  mutable TBranch *b_jets_AK4_btag_TC_highPur_;
  mutable bool c_jets_AK4_btag_TC_highPur_;
  mutable std::vector<float>* jets_AK4_btag_jetBProb_;
  mutable TBranch *b_jets_AK4_btag_jetBProb_;
  mutable bool c_jets_AK4_btag_jetBProb_;
  mutable std::vector<float>* jets_AK4_btag_jetProb_;
  mutable TBranch *b_jets_AK4_btag_jetProb_;
  mutable bool c_jets_AK4_btag_jetProb_;
  mutable std::vector<float>* jets_AK4_btag_secVertexCombined_;
  mutable TBranch *b_jets_AK4_btag_secVertexCombined_;
  mutable bool c_jets_AK4_btag_secVertexCombined_;
  mutable std::vector<float>* jets_AK4_btag_secVertexHighEff_;
  mutable TBranch *b_jets_AK4_btag_secVertexHighEff_;
  mutable bool c_jets_AK4_btag_secVertexHighEff_;
  mutable std::vector<float>* jets_AK4_btag_secVertexHighPur_;
  mutable TBranch *b_jets_AK4_btag_secVertexHighPur_;
  mutable bool c_jets_AK4_btag_secVertexHighPur_;
  mutable std::vector<float>* jets_AK4_btag_softEle_;
  mutable TBranch *b_jets_AK4_btag_softEle_;
  mutable bool c_jets_AK4_btag_softEle_;
  mutable std::vector<float>* jets_AK4_btag_softMuon_;
  mutable TBranch *b_jets_AK4_btag_softMuon_;
  mutable bool c_jets_AK4_btag_softMuon_;
  mutable std::vector<float>* jets_AK4_chgEmE_;
  mutable TBranch *b_jets_AK4_chgEmE_;
  mutable bool c_jets_AK4_chgEmE_;
  mutable std::vector<float>* jets_AK4_chgHadE_;
  mutable TBranch *b_jets_AK4_chgHadE_;
  mutable bool c_jets_AK4_chgHadE_;
  mutable std::vector<float>* jets_AK4_chgMuE_;
  mutable TBranch *b_jets_AK4_chgMuE_;
  mutable bool c_jets_AK4_chgMuE_;
  mutable std::vector<float>* jets_AK4_chg_Mult_;
  mutable TBranch *b_jets_AK4_chg_Mult_;
  mutable bool c_jets_AK4_chg_Mult_;
  mutable std::vector<float>* jets_AK4_corrFactorRaw_;
  mutable TBranch *b_jets_AK4_corrFactorRaw_;
  mutable bool c_jets_AK4_corrFactorRaw_;
  mutable std::vector<float>* jets_AK4_ehf_;
  mutable TBranch *b_jets_AK4_ehf_;
  mutable bool c_jets_AK4_ehf_;
  mutable std::vector<int>* jets_AK4_el_ind_;
  mutable TBranch *b_jets_AK4_el_ind_;
  mutable bool c_jets_AK4_el_ind_;
  mutable std::vector<float>* jets_AK4_emf_;
  mutable TBranch *b_jets_AK4_emf_;
  mutable bool c_jets_AK4_emf_;
  mutable std::vector<float>* jets_AK4_energy_;
  mutable TBranch *b_jets_AK4_energy_;
  mutable bool c_jets_AK4_energy_;
  mutable std::vector<float>* jets_AK4_et_;
  mutable TBranch *b_jets_AK4_et_;
  mutable bool c_jets_AK4_et_;
  mutable std::vector<float>* jets_AK4_eta_;
  mutable TBranch *b_jets_AK4_eta_;
  mutable bool c_jets_AK4_eta_;
  mutable std::vector<float>* jets_AK4_etaetaMoment_;
  mutable TBranch *b_jets_AK4_etaetaMoment_;
  mutable bool c_jets_AK4_etaetaMoment_;
  mutable std::vector<float>* jets_AK4_etaphiMoment_;
  mutable TBranch *b_jets_AK4_etaphiMoment_;
  mutable bool c_jets_AK4_etaphiMoment_;
  mutable std::vector<float>* jets_AK4_fHPD_;
  mutable TBranch *b_jets_AK4_fHPD_;
  mutable bool c_jets_AK4_fHPD_;
  mutable std::vector<float>* jets_AK4_fRBX_;
  mutable TBranch *b_jets_AK4_fRBX_;
  mutable bool c_jets_AK4_fRBX_;
  mutable std::vector<float>* jets_AK4_fSubDetector1_;
  mutable TBranch *b_jets_AK4_fSubDetector1_;
  mutable bool c_jets_AK4_fSubDetector1_;
  mutable std::vector<float>* jets_AK4_fSubDetector2_;
  mutable TBranch *b_jets_AK4_fSubDetector2_;
  mutable bool c_jets_AK4_fSubDetector2_;
  mutable std::vector<float>* jets_AK4_fSubDetector3_;
  mutable TBranch *b_jets_AK4_fSubDetector3_;
  mutable bool c_jets_AK4_fSubDetector3_;
  mutable std::vector<float>* jets_AK4_fSubDetector4_;
  mutable TBranch *b_jets_AK4_fSubDetector4_;
  mutable bool c_jets_AK4_fSubDetector4_;
  mutable std::vector<float>* jets_AK4_gen_Energy_;
  mutable TBranch *b_jets_AK4_gen_Energy_;
  mutable bool c_jets_AK4_gen_Energy_;
  mutable std::vector<float>* jets_AK4_gen_Id_;
  mutable TBranch *b_jets_AK4_gen_Id_;
  mutable bool c_jets_AK4_gen_Id_;
  mutable std::vector<float>* jets_AK4_gen_et_;
  mutable TBranch *b_jets_AK4_gen_et_;
  mutable bool c_jets_AK4_gen_et_;
  mutable std::vector<float>* jets_AK4_gen_eta_;
  mutable TBranch *b_jets_AK4_gen_eta_;
  mutable bool c_jets_AK4_gen_eta_;
  mutable std::vector<float>* jets_AK4_gen_mass_;
  mutable TBranch *b_jets_AK4_gen_mass_;
  mutable bool c_jets_AK4_gen_mass_;
  mutable std::vector<float>* jets_AK4_gen_motherID_;
  mutable TBranch *b_jets_AK4_gen_motherID_;
  mutable bool c_jets_AK4_gen_motherID_;
  mutable std::vector<float>* jets_AK4_gen_phi_;
  mutable TBranch *b_jets_AK4_gen_phi_;
  mutable bool c_jets_AK4_gen_phi_;
  mutable std::vector<float>* jets_AK4_gen_pt_;
  mutable TBranch *b_jets_AK4_gen_pt_;
  mutable bool c_jets_AK4_gen_pt_;
  mutable std::vector<float>* jets_AK4_gen_threeCharge_;
  mutable TBranch *b_jets_AK4_gen_threeCharge_;
  mutable bool c_jets_AK4_gen_threeCharge_;
  mutable std::vector<float>* jets_AK4_hitsInN90_;
  mutable TBranch *b_jets_AK4_hitsInN90_;
  mutable bool c_jets_AK4_hitsInN90_;
  mutable std::vector<float>* jets_AK4_jetCharge_;
  mutable TBranch *b_jets_AK4_jetCharge_;
  mutable bool c_jets_AK4_jetCharge_;
  mutable std::vector<float>* jets_AK4_mass_;
  mutable TBranch *b_jets_AK4_mass_;
  mutable bool c_jets_AK4_mass_;
  mutable std::vector<int>* jets_AK4_maxpt_id_;
  mutable TBranch *b_jets_AK4_maxpt_id_;
  mutable bool c_jets_AK4_maxpt_id_;
  mutable std::vector<float>* jets_AK4_mu_Mult_;
  mutable TBranch *b_jets_AK4_mu_Mult_;
  mutable bool c_jets_AK4_mu_Mult_;
  mutable std::vector<int>* jets_AK4_mu_ind_;
  mutable TBranch *b_jets_AK4_mu_ind_;
  mutable bool c_jets_AK4_mu_ind_;
  mutable std::vector<float>* jets_AK4_n60_;
  mutable TBranch *b_jets_AK4_n60_;
  mutable bool c_jets_AK4_n60_;
  mutable std::vector<float>* jets_AK4_n90_;
  mutable TBranch *b_jets_AK4_n90_;
  mutable bool c_jets_AK4_n90_;
  mutable std::vector<float>* jets_AK4_n90Hits_;
  mutable TBranch *b_jets_AK4_n90Hits_;
  mutable bool c_jets_AK4_n90Hits_;
  mutable std::vector<float>* jets_AK4_nECALTowers_;
  mutable TBranch *b_jets_AK4_nECALTowers_;
  mutable bool c_jets_AK4_nECALTowers_;
  mutable std::vector<float>* jets_AK4_nHCALTowers_;
  mutable TBranch *b_jets_AK4_nHCALTowers_;
  mutable bool c_jets_AK4_nHCALTowers_;
  mutable std::vector<float>* jets_AK4_neutralEmE_;
  mutable TBranch *b_jets_AK4_neutralEmE_;
  mutable bool c_jets_AK4_neutralEmE_;
  mutable std::vector<float>* jets_AK4_neutralHadE_;
  mutable TBranch *b_jets_AK4_neutralHadE_;
  mutable bool c_jets_AK4_neutralHadE_;
  mutable std::vector<float>* jets_AK4_neutral_Mult_;
  mutable TBranch *b_jets_AK4_neutral_Mult_;
  mutable bool c_jets_AK4_neutral_Mult_;
  mutable std::vector<float>* jets_AK4_partonFlavour_;
  mutable TBranch *b_jets_AK4_partonFlavour_;
  mutable bool c_jets_AK4_partonFlavour_;
  mutable std::vector<float>* jets_AK4_parton_Energy_;
  mutable TBranch *b_jets_AK4_parton_Energy_;
  mutable bool c_jets_AK4_parton_Energy_;
  mutable std::vector<float>* jets_AK4_parton_Id_;
  mutable TBranch *b_jets_AK4_parton_Id_;
  mutable bool c_jets_AK4_parton_Id_;
  mutable std::vector<float>* jets_AK4_parton_eta_;
  mutable TBranch *b_jets_AK4_parton_eta_;
  mutable bool c_jets_AK4_parton_eta_;
  mutable std::vector<float>* jets_AK4_parton_mass_;
  mutable TBranch *b_jets_AK4_parton_mass_;
  mutable bool c_jets_AK4_parton_mass_;
  mutable std::vector<float>* jets_AK4_parton_motherId_;
  mutable TBranch *b_jets_AK4_parton_motherId_;
  mutable bool c_jets_AK4_parton_motherId_;
  mutable std::vector<float>* jets_AK4_parton_phi_;
  mutable TBranch *b_jets_AK4_parton_phi_;
  mutable bool c_jets_AK4_parton_phi_;
  mutable std::vector<float>* jets_AK4_parton_pt_;
  mutable TBranch *b_jets_AK4_parton_pt_;
  mutable bool c_jets_AK4_parton_pt_;
  mutable std::vector<float>* jets_AK4_phi_;
  mutable TBranch *b_jets_AK4_phi_;
  mutable bool c_jets_AK4_phi_;
  mutable std::vector<float>* jets_AK4_phiphiMoment_;
  mutable TBranch *b_jets_AK4_phiphiMoment_;
  mutable bool c_jets_AK4_phiphiMoment_;
  mutable std::vector<float>* jets_AK4_photonEnergy_;
  mutable TBranch *b_jets_AK4_photonEnergy_;
  mutable bool c_jets_AK4_photonEnergy_;
  mutable std::vector<float>* jets_AK4_pt_;
  mutable TBranch *b_jets_AK4_pt_;
  mutable bool c_jets_AK4_pt_;
  mutable std::vector<float>* jets_AK4_px_;
  mutable TBranch *b_jets_AK4_px_;
  mutable bool c_jets_AK4_px_;
  mutable std::vector<float>* jets_AK4_py_;
  mutable TBranch *b_jets_AK4_py_;
  mutable bool c_jets_AK4_py_;
  mutable std::vector<float>* jets_AK4_pz_;
  mutable TBranch *b_jets_AK4_pz_;
  mutable bool c_jets_AK4_pz_;
  mutable std::vector<float>* jets_AK4_rawPt_;
  mutable TBranch *b_jets_AK4_rawPt_;
  mutable bool c_jets_AK4_rawPt_;
  mutable std::vector<float>* jets_AK4_status_;
  mutable TBranch *b_jets_AK4_status_;
  mutable bool c_jets_AK4_status_;
  mutable std::vector<float>* jets_AK4_theta_;
  mutable TBranch *b_jets_AK4_theta_;
  mutable bool c_jets_AK4_theta_;
  mutable std::vector<float>* mc_final_charge_;
  mutable TBranch *b_mc_final_charge_;
  mutable bool c_mc_final_charge_;
  mutable std::vector<float>* mc_final_energy_;
  mutable TBranch *b_mc_final_energy_;
  mutable bool c_mc_final_energy_;
  mutable std::vector<float>* mc_final_eta_;
  mutable TBranch *b_mc_final_eta_;
  mutable bool c_mc_final_eta_;
  mutable std::vector<float>* mc_final_ggrandmother_id_;
  mutable TBranch *b_mc_final_ggrandmother_id_;
  mutable bool c_mc_final_ggrandmother_id_;
  mutable std::vector<float>* mc_final_grandmother_id_;
  mutable TBranch *b_mc_final_grandmother_id_;
  mutable bool c_mc_final_grandmother_id_;
  mutable std::vector<float>* mc_final_id_;
  mutable TBranch *b_mc_final_id_;
  mutable bool c_mc_final_id_;
  mutable std::vector<float>* mc_final_mass_;
  mutable TBranch *b_mc_final_mass_;
  mutable bool c_mc_final_mass_;
  mutable std::vector<float>* mc_final_mother_id_;
  mutable TBranch *b_mc_final_mother_id_;
  mutable bool c_mc_final_mother_id_;
  mutable std::vector<float>* mc_final_mother_pt_;
  mutable TBranch *b_mc_final_mother_pt_;
  mutable bool c_mc_final_mother_pt_;
  mutable std::vector<float>* mc_final_numOfDaughters_;
  mutable TBranch *b_mc_final_numOfDaughters_;
  mutable bool c_mc_final_numOfDaughters_;
  mutable std::vector<float>* mc_final_numOfMothers_;
  mutable TBranch *b_mc_final_numOfMothers_;
  mutable bool c_mc_final_numOfMothers_;
  mutable std::vector<float>* mc_final_phi_;
  mutable TBranch *b_mc_final_phi_;
  mutable bool c_mc_final_phi_;
  mutable std::vector<float>* mc_final_pt_;
  mutable TBranch *b_mc_final_pt_;
  mutable bool c_mc_final_pt_;
  mutable std::vector<float>* mc_final_px_;
  mutable TBranch *b_mc_final_px_;
  mutable bool c_mc_final_px_;
  mutable std::vector<float>* mc_final_py_;
  mutable TBranch *b_mc_final_py_;
  mutable bool c_mc_final_py_;
  mutable std::vector<float>* mc_final_pz_;
  mutable TBranch *b_mc_final_pz_;
  mutable bool c_mc_final_pz_;
  mutable std::vector<float>* mc_final_status_;
  mutable TBranch *b_mc_final_status_;
  mutable bool c_mc_final_status_;
  mutable std::vector<float>* mc_final_theta_;
  mutable TBranch *b_mc_final_theta_;
  mutable bool c_mc_final_theta_;
  mutable std::vector<float>* mc_final_vertex_x_;
  mutable TBranch *b_mc_final_vertex_x_;
  mutable bool c_mc_final_vertex_x_;
  mutable std::vector<float>* mc_final_vertex_y_;
  mutable TBranch *b_mc_final_vertex_y_;
  mutable bool c_mc_final_vertex_y_;
  mutable std::vector<float>* mc_final_vertex_z_;
  mutable TBranch *b_mc_final_vertex_z_;
  mutable bool c_mc_final_vertex_z_;
  mutable std::vector<float>* mc_jets_auxiliaryEnergy_;
  mutable TBranch *b_mc_jets_auxiliaryEnergy_;
  mutable bool c_mc_jets_auxiliaryEnergy_;
  mutable std::vector<float>* mc_jets_emEnergy_;
  mutable TBranch *b_mc_jets_emEnergy_;
  mutable bool c_mc_jets_emEnergy_;
  mutable std::vector<float>* mc_jets_energy_;
  mutable TBranch *b_mc_jets_energy_;
  mutable bool c_mc_jets_energy_;
  mutable std::vector<float>* mc_jets_et_;
  mutable TBranch *b_mc_jets_et_;
  mutable bool c_mc_jets_et_;
  mutable std::vector<float>* mc_jets_eta_;
  mutable TBranch *b_mc_jets_eta_;
  mutable bool c_mc_jets_eta_;
  mutable std::vector<float>* mc_jets_etaetaMoment_;
  mutable TBranch *b_mc_jets_etaetaMoment_;
  mutable bool c_mc_jets_etaetaMoment_;
  mutable std::vector<float>* mc_jets_etaphiMoment_;
  mutable TBranch *b_mc_jets_etaphiMoment_;
  mutable bool c_mc_jets_etaphiMoment_;
  mutable std::vector<float>* mc_jets_hadEnergy_;
  mutable TBranch *b_mc_jets_hadEnergy_;
  mutable bool c_mc_jets_hadEnergy_;
  mutable std::vector<float>* mc_jets_invisibleEnergy_;
  mutable TBranch *b_mc_jets_invisibleEnergy_;
  mutable bool c_mc_jets_invisibleEnergy_;
  mutable std::vector<float>* mc_jets_mass_;
  mutable TBranch *b_mc_jets_mass_;
  mutable bool c_mc_jets_mass_;
  mutable std::vector<float>* mc_jets_phi_;
  mutable TBranch *b_mc_jets_phi_;
  mutable bool c_mc_jets_phi_;
  mutable std::vector<float>* mc_jets_phiphiMoment_;
  mutable TBranch *b_mc_jets_phiphiMoment_;
  mutable bool c_mc_jets_phiphiMoment_;
  mutable std::vector<float>* mc_jets_pt_;
  mutable TBranch *b_mc_jets_pt_;
  mutable bool c_mc_jets_pt_;
  mutable std::vector<float>* mc_jets_px_;
  mutable TBranch *b_mc_jets_px_;
  mutable bool c_mc_jets_px_;
  mutable std::vector<float>* mc_jets_py_;
  mutable TBranch *b_mc_jets_py_;
  mutable bool c_mc_jets_py_;
  mutable std::vector<float>* mc_jets_pz_;
  mutable TBranch *b_mc_jets_pz_;
  mutable bool c_mc_jets_pz_;
  mutable std::vector<float>* mc_jets_theta_;
  mutable TBranch *b_mc_jets_theta_;
  mutable bool c_mc_jets_theta_;
  mutable std::vector<float>* mets_et_;
  mutable TBranch *b_mets_et_;
  mutable bool c_mets_et_;
  mutable std::vector<float>* mets_ex_;
  mutable TBranch *b_mets_ex_;
  mutable bool c_mets_ex_;
  mutable std::vector<float>* mets_ey_;
  mutable TBranch *b_mets_ey_;
  mutable bool c_mets_ey_;
  mutable std::vector<float>* mets_gen_et_;
  mutable TBranch *b_mets_gen_et_;
  mutable bool c_mets_gen_et_;
  mutable std::vector<float>* mets_gen_phi_;
  mutable TBranch *b_mets_gen_phi_;
  mutable bool c_mets_gen_phi_;
  mutable std::vector<float>* mets_phi_;
  mutable TBranch *b_mets_phi_;
  mutable bool c_mets_phi_;
  mutable std::vector<float>* mets_sign_;
  mutable TBranch *b_mets_sign_;
  mutable bool c_mets_sign_;
  mutable std::vector<float>* mets_sumEt_;
  mutable TBranch *b_mets_sumEt_;
  mutable bool c_mets_sumEt_;
  mutable std::vector<float>* mets_unCPhi_;
  mutable TBranch *b_mets_unCPhi_;
  mutable bool c_mets_unCPhi_;
  mutable std::vector<float>* mets_unCPt_;
  mutable TBranch *b_mets_unCPt_;
  mutable bool c_mets_unCPt_;
  mutable std::vector<bool>* mus_isPF_;
  mutable TBranch *b_mus_isPF_;
  mutable bool c_mus_isPF_;
  mutable std::vector<int>* mus_jet_ind_;
  mutable TBranch *b_mus_jet_ind_;
  mutable bool c_mus_jet_ind_;
  mutable std::vector<int>* taus_el_ind_;
  mutable TBranch *b_taus_el_ind_;
  mutable bool c_taus_el_ind_;
  mutable std::vector<int>* taus_mu_ind_;
  mutable TBranch *b_taus_mu_ind_;
  mutable bool c_taus_mu_ind_;
  mutable std::vector<bool>* trigger_decision_;
  mutable TBranch *b_trigger_decision_;
  mutable bool c_trigger_decision_;
  mutable Int_t trkPOG_logErrorTooManyClustersfilter_decision_;
  mutable TBranch *b_trkPOG_logErrorTooManyClustersfilter_decision_;
  mutable bool c_trkPOG_logErrorTooManyClustersfilter_decision_;
  mutable Int_t trkPOG_manystripclus53Xfilter_decision_;
  mutable TBranch *b_trkPOG_manystripclus53Xfilter_decision_;
  mutable bool c_trkPOG_manystripclus53Xfilter_decision_;
  mutable Int_t trkPOG_toomanystripclus53Xfilter_decision_;
  mutable TBranch *b_trkPOG_toomanystripclus53Xfilter_decision_;
  mutable bool c_trkPOG_toomanystripclus53Xfilter_decision_;
  mutable Int_t trkPOGfilter_decision_;
  mutable TBranch *b_trkPOGfilter_decision_;
  mutable bool c_trkPOGfilter_decision_;
};

#endif
